# Homebrew bundle file — reproduces the formulae/casks this setup depends on.
# Install everything with: brew bundle --file=~/dotfiles/Brewfile

# --- CLI tools ---
brew "asciinema"
brew "autojump"
brew "awscli"
brew "bash"
brew "bat"
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "fzf"
brew "git"
brew "gnupg"
brew "helm"
brew "jq"
brew "jsonnet"
brew "kind"
brew "kubeseal"
brew "kubie"
brew "minikube"
brew "neovim"
brew "node"
brew "openssh"
brew "pinentry-mac"
brew "pyenv"
brew "terraform"
brew "tfenv"
brew "tmux"
brew "tree"
brew "uv"
brew "vim"
brew "yarn"
brew "yq"
brew "zoxide"

# --- Casks ---
cask "claude-code"
cask "firefox"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "ghostty"
cask "microsoft-teams"
cask "spotify"
cask "zed"
